import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
    Pill,
    ClipboardList,
    Calendar,
    Clock,
    User,
    Download,
    AlertCircle,
    Activity,
    ChevronRight,
    CheckCircle2,
    XCircle,
    History
} from "lucide-react";
import { API_BASE_URL } from "@/lib/config";
import { useAuth } from "@/context/AuthContext";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

export default function PatientPrescriptions() {
    const { user } = useAuth();
    const [prescriptions, setPrescriptions] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchPrescriptions = async () => {
            if (!user?.id) return;
            try {
                const res = await fetch(`${API_BASE_URL}/prescriptions/read.php?patient_id=${user.id}`);
                const data = await res.json();
                if (data.success) {
                    setPrescriptions(data.prescriptions);
                }
            } catch (error) {
                console.error("Error fetching prescriptions:", error);
                toast.error("Failed to load clinical prescriptions.");
            } finally {
                setLoading(false);
            }
        };

        fetchPrescriptions();
    }, [user?.id]);

    const activePrescriptions = prescriptions.filter(p => p.status === 'active');
    const pastPrescriptions = prescriptions.filter(p => p.status !== 'active');

    return (
        <div className="space-y-10 animate-fade-in pb-20">
            <div>
                <h1 className="text-4xl md:text-5xl font-black tracking-tighter text-white italic uppercase">
                    Digital <span className="text-[hsl(var(--gold))]">Prescriptions</span>
                </h1>
                <p className="text-white/40 font-medium mt-2 max-w-2xl">
                    View and manage your active medications and prescription history generated by our clinical team.
                </p>
            </div>

            {/* Active Prescriptions */}
            <section className="space-y-6">
                <div className="flex items-center gap-3">
                    <Activity className="h-5 w-5 text-emerald-500 shadow-glow-emerald" />
                    <h2 className="text-sm font-black uppercase tracking-[0.3em] text-white/60">Active Treatment Plan</h2>
                </div>

                {loading ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {[1, 2].map(i => (
                            <div key={i} className="h-48 rounded-[2.5rem] bg-white/5 border border-white/5 animate-pulse" />
                        ))}
                    </div>
                ) : activePrescriptions.length > 0 ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {activePrescriptions.map((rx) => (
                            <Card key={rx.id} className="glass-card border-white/10 overflow-hidden group hover:border-[hsl(var(--gold))]/30 transition-all duration-500 rounded-[2.5rem]">
                                <CardContent className="p-8">
                                    <div className="flex items-start justify-between mb-6">
                                        <div className="flex items-center gap-4">
                                            <div className="h-14 w-14 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center group-hover:bg-[hsl(var(--gold))]/10 transition-colors">
                                                <Pill className="h-7 w-7 text-[hsl(var(--gold))]" />
                                            </div>
                                            <div>
                                                <h3 className="text-xl font-black text-white italic tracking-tight">{rx.medication}</h3>
                                                <p className="text-[10px] font-black uppercase tracking-widest text-[hsl(var(--gold))]/60">#{rx.id} • Authorized</p>
                                            </div>
                                        </div>
                                        <div className="px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-[9px] font-black uppercase tracking-widest text-emerald-500">
                                            In Effect
                                        </div>
                                    </div>

                                    <div className="space-y-4 mb-8">
                                        <div className="flex items-center gap-3 text-white/60">
                                            <Clock className="h-4 w-4 text-[hsl(var(--gold))]" />
                                            <span className="text-xs font-bold">{rx.dosage}</span>
                                        </div>
                                        <div className="flex items-start gap-3 text-white/40">
                                            <ClipboardList className="h-4 w-4 text-[hsl(var(--gold))] shrink-0 mt-0.5" />
                                            <p className="text-xs font-medium leading-relaxed">{rx.instructions || "No specific instructions provided."}</p>
                                        </div>
                                    </div>

                                    <div className="pt-6 border-t border-white/5 flex items-center justify-between">
                                        <div className="flex items-center gap-2">
                                            <div className="h-8 w-8 rounded-full bg-white/5 flex items-center justify-center">
                                                <User className="h-4 w-4 text-white/20" />
                                            </div>
                                            <div className="text-[9px] font-black uppercase tracking-widest text-white/30">
                                                Dr. {rx.doctor_name}
                                            </div>
                                        </div>
                                        <Button
                                            variant="ghost"
                                            className="h-10 px-4 rounded-xl text-[9px] font-black uppercase tracking-widest text-white/40 hover:text-white hover:bg-white/5 gap-2"
                                            onClick={() => toast.info("Preparing digital copy...")}
                                        >
                                            <Download className="h-3.5 w-3.5" /> PDF
                                        </Button>
                                    </div>
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                ) : (
                    <div className="p-12 text-center rounded-[3rem] border border-dashed border-white/10 bg-white/5">
                        <AlertCircle className="h-10 w-10 text-white/10 mx-auto mb-4" />
                        <h3 className="text-lg font-black text-white/20 uppercase tracking-widest italic">No Active Prescriptions</h3>
                        <p className="text-xs text-white/30 font-medium mt-2">Any medications authorized by your doctor will appear here.</p>
                    </div>
                )}
            </section>

            {/* Past History */}
            <section className="space-y-6 pt-10">
                <div className="flex items-center gap-3">
                    <History className="h-5 w-5 text-white/20" />
                    <h2 className="text-sm font-black uppercase tracking-[0.3em] text-white/40">Treatment History</h2>
                </div>

                <div className="glass-card border-white/5 rounded-[3rem] overflow-hidden">
                    <div className="divide-y divide-white/5">
                        {pastPrescriptions.length > 0 ? (
                            pastPrescriptions.map((rx) => (
                                <div key={rx.id} className="p-8 hover:bg-white/[0.02] transition-colors flex items-center justify-between group">
                                    <div className="flex items-center gap-6">
                                        <div className="h-12 w-12 rounded-xl bg-white/5 flex items-center justify-center text-white/10">
                                            <CheckCircle2 className="h-6 w-6" />
                                        </div>
                                        <div>
                                            <h4 className="font-bold text-white/80 text-lg italic tracking-tight">{rx.medication}</h4>
                                            <p className="text-[10px] font-black uppercase tracking-widest text-white/30 mt-1">
                                                Prescribed: {new Date(rx.date_prescribed).toLocaleDateString()} • Dr. {rx.doctor_name}
                                            </p>
                                        </div>
                                    </div>
                                    <Button variant="ghost" className="rounded-xl h-10 w-10 p-0 text-white/10 hover:text-white hover:bg-white/5">
                                        <ChevronRight className="h-5 w-5" />
                                    </Button>
                                </div>
                            ))
                        ) : (
                            <div className="p-16 text-center text-[10px] font-black uppercase tracking-widest text-white/10">
                                No past treatment records found.
                            </div>
                        )}
                    </div>
                </div>
            </section>

            <div className="p-10 rounded-[3rem] bg-gradient-to-br from-[hsl(var(--gold))]/5 to-transparent border border-[hsl(var(--gold))]/10">
                <div className="flex flex-col md:flex-row items-center gap-8">
                    <div className="h-20 w-20 rounded-[2.5rem] bg-[hsl(var(--gold))]/10 flex items-center justify-center shadow-glow-gold flex-shrink-0">
                        <Pill className="h-10 w-10 text-[hsl(var(--gold))]" />
                    </div>
                    <div>
                        <h3 className="text-xl font-black text-white italic tracking-tight mb-2">Clinical Note</h3>
                        <p className="text-sm text-white/50 leading-relaxed max-w-2xl font-medium">
                            Only take medications as directed by your healthcare professional. If you experience adverse reactions, please contact our emergency line immediately or visit the nearest clinical branch.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
