-- Add 'category' column to notifications table for categorized alerts
-- Categories: general, role_based, individual, system
ALTER TABLE notifications 
ADD COLUMN IF NOT EXISTS category VARCHAR(50) DEFAULT 'general',
ADD COLUMN IF NOT EXISTS sent_by_id INT NULL,
ADD COLUMN IF NOT EXISTS sent_by_name VARCHAR(255) NULL;

-- Update existing rows to 'general' category
UPDATE notifications SET category = 'general' WHERE category IS NULL;

/* 
  Category meanings:
  - general:    Broadcast to everyone (all users)
  - role_based: Sent to a specific role (doctor or patient group)
  - individual: Sent to a specific person (doctor → patient, admin → specific user)
  - system:     Auto-generated by system events (appointment confirmations etc.)
*/
